# Data audit using reusable cleaning functions

The first code cell below imports the reusable functions from
[`src/team_wtm/cleaning.py`](../src/team_wtm/cleaning.py). This notebook calls those
functions to load, merge, inspect and clean the data rather than duplicating
their implementation.

Install the project package with `uv sync`, then run all cells in order using
the project environment. The working directory
can be the project root or `notebooks/`. Raw CSV files must be in `data/raw/`.
`train_data` remains the raw merged dataset; `cleaned_data` contains the result
of the shared cleaning rules. This notebook does not write datasets to disk.

In [1]:
from IPython.display import display

# Import the installed project package; maintain shared rules in cleaning.py.
from team_wtm.cleaning import (
    build_data_dictionary,
    check_data_quality,
    check_suspicious_values,
    clean_data,
    inspect_categorical_variants,
    inspect_columns,
    investigate_duplicates,
    load_data,
    merge_data,
)

# Default paths are resolved by the module; IDs are validated before merging.
train_values, train_label = load_data()

## Dataset dimensions and structure

In [2]:
print("train_values_shape:", train_values.shape)
print("train_label_shape:", train_label.shape)

train_values_shape: (59400, 40)
train_label_shape: (59400, 2)

In [3]:
train_values.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  str
 3   funder                 55763 non-null  str
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  str
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  str
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  str
 11  subvillage             59029 non-null  str
 12  region                 59400 non-null  str
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  str
 16  ward                   59400 non-null  str
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  str
 20  scheme_management      55522 non-null  str
 21  scheme_name            30590 non-null  str
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  str
 25  extraction_type_group  59400 non-null  str
 26  extraction_type_class  59400 non-null  str
 27  management             59400 non-null  str
 28  management_group       59400 non-null  str
 29  payment                59400 non-null  str
 30  payment_type           59400 non-null  str
 31  water_quality          59400 non-null  str
 32  quality_group          59400 non-null  str
 33  quantity               59400 non-null  str
 34  quantity_group         59400 non-null  str
 35  source                 59400 non-null  str
 36  source_type            59400 non-null  str
 37  source_class           59400 non-null  str
 38  waterpoint_type        59400 non-null  str
 39  waterpoint_type_group  59400 non-null  str
dtypes: float64(3), int64(7), object(2), str(28)
memory usage: 32.2+ MB

In [4]:
train_label.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            59400 non-null  int64
 1   status_group  59400 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.6 MB

In [5]:
print("Unique IDs in labels:", train_label["id"].nunique())
print("Unique IDs in values:", train_values["id"].nunique())

Unique IDs in labels: 59400
Unique IDs in values: 59400

## Merge the datasets

Use an outer join to keep unmatched IDs visible. Review the merge counts before
removing the diagnostic `_merge` column. Investigate unmatched IDs before
modelling; they are retained in this audit rather than silently removed.

In [6]:
train_data = merge_data(train_values, train_label, keep_merge_indicator=True)

In [7]:
merge_counts = train_data["_merge"].value_counts()
display(merge_counts.rename("Rows by merge outcome"))
train_data = train_data.drop(columns="_merge")

_merge
both          59400
left_only         0
right_only        0
Name: Rows by merge outcome, dtype: int64

In [8]:
train_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  str
 3   funder                 55763 non-null  str
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  str
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  str
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  str
 11  subvillage             59029 non-null  str
 12  region                 59400 non-null  str
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  str
 16  ward                   59400 non-null  str
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  str
 20  scheme_management      55522 non-null  str
 21  scheme_name            30590 non-null  str
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  str
 25  extraction_type_group  59400 non-null  str
 26  extraction_type_class  59400 non-null  str
 27  management             59400 non-null  str
 28  management_group       59400 non-null  str
 29  payment                59400 non-null  str
 30  payment_type           59400 non-null  str
 31  water_quality          59400 non-null  str
 32  quality_group          59400 non-null  str
 33  quantity               59400 non-null  str
 34  quantity_group         59400 non-null  str
 35  source                 59400 non-null  str
 36  source_type            59400 non-null  str
 37  source_class           59400 non-null  str
 38  waterpoint_type        59400 non-null  str
 39  waterpoint_type_group  59400 non-null  str
 40  status_group           59400 non-null  str
dtypes: float64(3), int64(7), object(2), str(29)
memory usage: 33.5+ MB

In [9]:
print("Merged dimensions:", train_data.shape)

Merged dimensions: (59400, 41)

In [10]:
display(train_data.head(10))

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,0,0.0,2012-11-13,Tasaf,0,TASAF,33.125828,-5.118154,Mratibu,0,...,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,non functional
1,1,0.0,2011-03-05,Shipo,1978,SHIPO,34.770717,-9.395642,none,0,...,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
2,2,0.0,2011-03-27,Lvia,0,LVIA,36.115056,-6.279268,Bombani,0,...,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,functional
3,3,10.0,2013-06-03,Germany Republi,1639,CES,37.147432,-3.187555,Area 7 Namba 5,0,...,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
4,4,0.0,2011-03-22,Cmsr,0,CMSR,36.164893,-6.099289,Ezeleda,0,...,soft,good,dry,dry,shallow well,shallow well,groundwater,hand pump,hand pump,non functional
5,5,50.0,2011-02-26,Private,28,Private,39.286124,-6.972403,Kwa Namaj,0,...,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,functional
6,6,0.0,2012-10-20,Government Of Tanzania,0,Government,33.229880,-3.852983,Mission,0,...,soft,good,seasonal,seasonal,shallow well,shallow well,groundwater,other,other,non functional
7,7,0.0,2011-03-23,Water,0,Gover,36.313619,-6.719257,Itawi,0,...,milky,milky,insufficient,insufficient,spring,spring,groundwater,improved spring,improved spring,functional
8,8,0.0,2011-04-07,Water,0,Commu,35.939445,-6.014358,Kwa Chiswagala,0,...,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
9,9,0.0,2011-07-12,Ded,0,DED,31.693371,-2.530703,Shule Ya Msingi Nyamirembe A,0,...,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional

In [11]:
display(train_data.dtypes.rename("Data type"))

id                         int64
amount_tsh               float64
date_recorded                str
funder                       str
gps_height                 int64
installer                    str
longitude                float64
latitude                 float64
wpt_name                     str
num_private                int64
basin                        str
subvillage                   str
region                       str
region_code                int64
district_code              int64
lga                          str
ward                         str
population                 int64
public_meeting            object
recorded_by                  str
scheme_management            str
scheme_name                  str
permit                    object
construction_year          int64
extraction_type              str
extraction_type_group        str
extraction_type_class        str
management                   str
management_group             str
payment                      str
payment_type                 str
water_quality                str
quality_group                str
quantity                     str
quantity_group               str
source                       str
source_type                  str
source_class                 str
waterpoint_type              str
waterpoint_type_group        str
status_group                 str
Name: Data type, dtype: object

In [12]:
rawdata_dictionary = build_data_dictionary(train_data)
display(rawdata_dictionary)

                   Column Data Type  Missing Values  Unique Values
0                      id     int64               0          59400
1              amount_tsh   float64               0             98
2           date_recorded       str               0            356
3                  funder       str            3637           1896
4              gps_height     int64               0           2428
5               installer       str            3655           2145
6               longitude   float64               0          57516
7                latitude   float64               0          57517
8                wpt_name       str               2          37399
9             num_private     int64               0             65
10                  basin       str               0              9
11             subvillage       str             371          19287
12                 region       str               0             21
13            region_code     int64               0             27
14          district_code     int64               0             20
15                    lga       str               0            125
16                   ward       str               0           2092
17             population     int64               0           1049
18         public_meeting    object            3334              2
19            recorded_by       str               0              1
20      scheme_management       str            3878             11
21            scheme_name       str           28810           2695
22                 permit    object            3056              2
23      construction_year     int64               0             55
24        extraction_type       str               0             18
25  extraction_type_group       str               0             13
26  extraction_type_class       str               0              7
27             management       str               0             12
28       management_group       str               0              5
29                payment       str               0              7
30           payment_type       str               0              7
31          water_quality       str               0              8
32          quality_group       str               0              6
33               quantity       str               0              5
34         quantity_group       str               0              5
35                 source       str               0             10
36            source_type       str               0              7
37           source_class       str               0              3
38        waterpoint_type       str               0              7
39  waterpoint_type_group       str               0              6
40           status_group       str               0              3

## Raw data quality checks

In [13]:
# Reuse the shared report for missing values, duplicates and target counts.
raw_quality = check_data_quality(train_data, verbose=False)
missing = raw_quality["missing_values"]
display(missing.rename("Missing values"))
print("Duplicate rows excluding id:", raw_quality["duplicate_rows"])

scheme_name              28810
scheme_management         3878
installer                 3655
funder                    3637
public_meeting            3334
permit                    3056
subvillage                 371
wpt_name                     2
id                           0
latitude                     0
longitude                    0
date_recorded                0
gps_height                   0
amount_tsh                   0
num_private                  0
basin                        0
region                       0
ward                         0
lga                          0
district_code                0
region_code                  0
recorded_by                  0
population                   0
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group                 0
Name: Missing values, dtype: int64

Duplicate rows excluding id: 36

### Duplicate observations and conflicting labels

Count repeated observations excluding `id`, then compare features excluding both
`id` and `status_group`. The second comparison detects identical feature records
with different labels. Counts of repeated rows exclude the first occurrence;
rows in duplicate groups include every member. Missing features participate in
the comparison. Group numbers refer only to this report.

Retain the records for this audit: different IDs may represent separate pumps.
Review the conflicting-label group with the source before deduplication. During
modelling, consider grouping identical feature records into the same validation
fold to reduce leakage; do not silently remove or relabel them.

In [14]:
duplicate_report = investigate_duplicates(train_data)
display(duplicate_report["summary"].to_frame())
duplicate_groups = duplicate_report["groups"]
display(duplicate_groups.head(20))
display(duplicate_groups.loc[duplicate_groups["Conflicting labels"]])

                                                  Count
Repeated observations excluding id                   36
Repeated feature rows excluding id and target        37
Feature duplicate groups                             35
Rows in feature duplicate groups                     72
Feature duplicate groups with conflicting labels      1

       Rows  Distinct labels  Conflicting labels
Group
408       2                2                True
515       2                1               False
1005      2                1               False
1258      2                1               False
1740      2                1               False
1752      2                1               False
1853      2                1               False
2688      2                1               False
3070      2                1               False
3435      2                1               False
3609      3                1               False
4923      2                1               False
6028      2                1               False
6329      3                1               False
6681      2                1               False
9395      2                1               False
11024     2                1               False
13144     2                1               False
13184     2                1               False
13587     2                1               False

       Rows  Distinct labels  Conflicting labels
Group
408       2                2                True

The missing-value report describes the raw data before cleaning. Zero placeholders
are counted separately below because they are not yet represented as missing.

In [15]:
display(raw_quality["target_distribution"].rename("Pump count"))

status_group
functional                 32259
non functional             22824
functional needs repair     4317
Name: Pump count, dtype: int64

The training classes are imbalanced: `functional needs repair` has fewer examples
than the other classes. Consider class-specific performance during modelling.
Missing target labels, if any, remain visible in the shared quality report.

In [16]:
# The shared inspector handles object, string and categorical dtypes.
column_summary = inspect_columns(train_data, verbose=False)
categorical_columns = column_summary["categorical_columns"]
print("Categorical columns:", categorical_columns)

Categorical columns: ['funder', 'installer', 'wpt_name', 'basin', 'subvillage', 'region', 'lga', 'ward', 'public_meeting', 'recorded_by', 'scheme_management', 'scheme_name', 'permit', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type', 'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 'waterpoint_type_group', 'status_group']

`inspect_columns()` excludes `date_recorded` from categorical inspection because
it represents a date. Setting `verbose=False` lets the notebook display each
returned summary separately.

In [17]:
# Limit previews for high-cardinality fields such as installer and waterpoint name.
for column in categorical_columns:
    unique_values = train_data[column].dropna().unique()
    print(f"\n{column}: {len(unique_values):,} unique non-missing values")
    print(unique_values[:20])
    if len(unique_values) > 20:
        print("Showing the first 20 values; see the cardinality table for totals.")

funder: 1,896 unique non-missing values
<ArrowStringArray>
[                  'Tasaf',                   'Shipo',
                    'Lvia',         'Germany Republi',
                    'Cmsr',                 'Private',
  'Government Of Tanzania',                   'Water',
                     'Ded',              'Kwa Makala',
              'World Bank',                  'Hesawa',
 'Songea District Council',                   'Amref',
                   'Oxfam',                      'Ir',
          'Roman Catholic',                  'Tassaf',
                    'Kkkt',                  'Danida']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

installer: 2,145 unique non-missing values
<ArrowStringArray>
[       'TASAF',        'SHIPO',         'LVIA',          'CES',
         'CMSR',      'Private',   'Government',        'Gover',
        'Commu',          'DED',       'Makala',   'World bank',
          'DWE',        'Amref',        'OXFAM',        'GOVER',
           'Ir',       'TASSAF', 'RUVUMA BASIN',         'KKKT']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

wpt_name: 37,399 unique non-missing values
<ArrowStringArray>
[                     'Mratibu',                         'none',
                      'Bombani',               'Area 7 Namba 5',
                      'Ezeleda',                    'Kwa Namaj',
                      'Mission',                        'Itawi',
               'Kwa Chiswagala', 'Shule Ya Msingi Nyamirembe A',
                   'Kwa Makala',       'Moivaro Primary School',
                     'Kwamazoa',                'Kwa Feristasi',
                        'Seuli',                   'Kwa Majele',
             'Kwa Ally Likomba',                          'Ccm',
                   'Salum Sady',                    'Kwa Konde']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

basin: 9 unique non-missing values
<ArrowStringArray>
[        'Lake Tanganyika',                  'Rufiji',
             'Wami / Ruvu',                 'Pangani',
                'Internal',           'Lake Victoria',
              'Lake Nyasa', 'Ruvuma / Southern Coast',
              'Lake Rukwa']
Length: 9, dtype: str

subvillage: 19,287 unique non-missing values
<ArrowStringArray>
[        'Majengo',        'Magoda C',      'Songambele',         'Urereni',
         'Maata A',        'Mwandege',      'Ngaganulwa',        'Mwangaza',
         'Mazengo',        'Miembeni',          'Sokoni',         'Moivaro',
        'Madukani',     'Amka Twende',           'Seuli',          'Mwenge',
      'Gwandamula',    'Manzilanzi A', 'Mtaa Wa Tungini',     'Mbuyuni Juu']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

region: 21 unique non-missing values
<ArrowStringArray>
[       'Tabora',        'Iringa',        'Dodoma',   'Kilimanjaro',
         'Pwani',     'Shinyanga',        'Kagera',         'Tanga',
        'Arusha',        'Mwanza',        'Ruvuma',        'Mtwara',
        'Kigoma', 'Dar es Salaam',      'Morogoro',         'Mbeya',
          'Mara',         'Lindi',       'Singida',         'Rukwa']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

lga: 125 unique non-missing values
<ArrowStringArray>
[           'Uyui',          'Njombe',        'Chamwino',             'Hai',
        'Mkuranga', 'Shinyanga Rural',         'Mpwapwa',    'Dodoma Urban',
           'Chato',         'Pangani',            'Meru',            'Magu',
    'Songea Rural',    'Arusha Rural',          'Kongwa',    'Mtwara Rural',
          'Kasulu',           'Ilala',          'Kilosa',          'Muheza']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

ward: 2,092 unique non-missing values
<ArrowStringArray>
[         'Igalula',           'Uwemba',          'Msamalo',
 'Masama Magharibi',         'Majeleko',          'Vikindu',
           'Usanda',            'Wotta',            'Ipala',
       'Nyamirembe',          'Mkalamo',         'Nkoanrua',
        'Igalukilo',         'Kilagano',         'Oltrumet',
          'Ugogoni',          'Njengwa',            'Janda',
          'Chanika',            'Ulaya']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

public_meeting: 2 unique non-missing values
[True False]

recorded_by: 1 unique non-missing values
<ArrowStringArray>
['GeoData Consultants Ltd']
Length: 1, dtype: str

scheme_management: 11 unique non-missing values
<ArrowStringArray>
[             'VWC',      'Water Board', 'Private operator',
              'WUA',  'Water authority',              'WUG',
            'Other',          'Company',       'Parastatal',
              'SWC',            'Trust']
Length: 11, dtype: str

scheme_name: 2,695 unique non-missing values
<ArrowStringArray>
[                          'Mgun',         'Losaa-Kia water supply',
                           'Lwih',                           'Ipal',
                      'Mapinduzi',           'Mkalamo water supply',
      'Mradi wa maji wa kilagano',              'Mlimani pipe line',
                           'Msin',       'Nang'awanga water supply',
                        'Mwangwe',                           'Manz',
           'Mabula mountains spr',                         'TASSAF',
                     'Government',                              'M',
     'Olchoronyokye water projec', 'Naluwale/Mkwajuni Water Supply',
                             'FW',                       'Endawasu']
Length: 20, dtype: str
Showing the first 20 values; see the cardinality table for totals.

permit: 2 unique non-missing values
[True False]

extraction_type: 18 unique non-missing values
<ArrowStringArray>
[                  'afridev',         'other - rope pump',
                      'mono',                   'gravity',
               'nira/tanira',               'submersible',
                     'other',                    'swn 80',
                  'windmill',             'india mark ii',
                       'ksb',                      'cemo',
            'india mark iii',            'other - swn 81',
                    'climax',         'other - play pump',
                    'walimi', 'other - mkulima/shinyanga']
Length: 18, dtype: str

extraction_type_group: 13 unique non-missing values
<ArrowStringArray>
[        'afridev',       'rope pump',            'mono',         'gravity',
     'nira/tanira',     'submersible',           'other',          'swn 80',
    'wind-powered',   'india mark ii', 'other motorpump',  'india mark iii',
  'other handpump']
Length: 13, dtype: str

extraction_type_class: 7 unique non-missing values
<ArrowStringArray>
[    'handpump',    'rope pump',    'motorpump',      'gravity',
  'submersible',        'other', 'wind-powered']
Length: 7, dtype: str

management: 12 unique non-missing values
<ArrowStringArray>
[             'vwc',      'water board', 'private operator',
              'wua',              'wug',          'company',
  'water authority',            'other',          'unknown',
       'parastatal',            'trust',   'other - school']
Length: 12, dtype: str

management_group: 5 unique non-missing values
<ArrowStringArray>
['user-group', 'commercial', 'other', 'unknown', 'parastatal']
Length: 5, dtype: str

payment: 7 unique non-missing values
<ArrowStringArray>
[              'unknown',             'never pay',        'pay per bucket',
 'pay when scheme fails',           'pay monthly',          'pay annually',
                 'other']
Length: 7, dtype: str

payment_type: 7 unique non-missing values
<ArrowStringArray>
[   'unknown',  'never pay', 'per bucket', 'on failure',    'monthly',
   'annually',      'other']
Length: 7, dtype: str

water_quality: 8 unique non-missing values
<ArrowStringArray>
[             'milky',               'soft',              'salty',
    'salty abandoned',           'coloured',            'unknown',
           'fluoride', 'fluoride abandoned']
Length: 8, dtype: str

quality_group: 6 unique non-missing values
<ArrowStringArray>
['milky', 'good', 'salty', 'colored', 'unknown', 'fluoride']
Length: 6, dtype: str

quantity: 5 unique non-missing values
<ArrowStringArray>
['enough', 'insufficient', 'dry', 'seasonal', 'unknown']
Length: 5, dtype: str

quantity_group: 5 unique non-missing values
<ArrowStringArray>
['enough', 'insufficient', 'dry', 'seasonal', 'unknown']
Length: 5, dtype: str

source: 10 unique non-missing values
<ArrowStringArray>
[        'shallow well',          'machine dbh',               'spring',
 'rainwater harvesting',                'river',                 'lake',
                'other',                  'dam',             'hand dtw',
              'unknown']
Length: 10, dtype: str

source_type: 7 unique non-missing values
<ArrowStringArray>
[        'shallow well',             'borehole',               'spring',
 'rainwater harvesting',           'river/lake',                'other',
                  'dam']
Length: 7, dtype: str

source_class: 3 unique non-missing values
<ArrowStringArray>
['groundwater', 'surface', 'unknown']
Length: 3, dtype: str

waterpoint_type: 7 unique non-missing values
<ArrowStringArray>
[                  'hand pump', 'communal standpipe multiple',
          'communal standpipe',                       'other',
             'improved spring',               'cattle trough',
                         'dam']
Length: 7, dtype: str

waterpoint_type_group: 6 unique non-missing values
<ArrowStringArray>
[         'hand pump', 'communal standpipe',              'other',
    'improved spring',      'cattle trough',                'dam']
Length: 6, dtype: str

status_group: 3 unique non-missing values
<ArrowStringArray>
['non functional', 'functional', 'functional needs repair']
Length: 3, dtype: str

Some features describe related information at different levels of detail:

| Feature | Related feature |
|---|---|
| `funder` | `installer` |
| `source` | `source_type` |
| `quantity` | `quantity_group` |
| `water_quality` | `quality_group` |
| `extraction_type` | `extraction_type_group` |
| `waterpoint_type` | `waterpoint_type_group` |
| `management` | `management_group` |

Related meaning does not prove that columns are identical. Further investigation
is needed before dropping these features; the shared cleaner retains them.
Cardinality counts below exclude missing values, which are reported separately.

In [18]:
cardinality_summary = column_summary["cardinality_summary"]
display(cardinality_summary)

                       Unique Values  Missing Values
wpt_name                       37399               2
subvillage                     19287             371
scheme_name                     2695           28810
installer                       2145            3655
ward                            2092               0
funder                          1896            3637
lga                              125               0
region                            21               0
extraction_type                   18               0
extraction_type_group             13               0
management                        12               0
scheme_management                 11            3878
source                            10               0
basin                              9               0
water_quality                      8               0
waterpoint_type                    7               0
source_type                        7               0
payment                            7               0
payment_type                       7               0
extraction_type_class              7               0
waterpoint_type_group              6               0
quality_group                      6               0
quantity                           5               0
quantity_group                     5               0
management_group                   5               0
source_class                       3               0
status_group                       3               0
public_meeting                     2            3334
permit                             2            3056
recorded_by                        1               0

### Inconsistent categorical spellings

Find candidate aliases that differ only in letter case or whitespace. Report
the number of groups and affected rows per column, then show a bounded preview.
These are candidates, not confirmed entity matches. Keep the raw values while
building a reviewed mapping for later preprocessing. Abbreviations and spelling
variants require further source review; `funder` and `installer` have different
roles and should not be treated as interchangeable.

In [19]:
categorical_variants = inspect_categorical_variants(train_data)
variant_summary = categorical_variants.groupby("Column").agg(
    Groups=("Normalized", "size"), Rows=("Rows", "sum")
)
display(variant_summary)
display(categorical_variants.head(20))

             Groups   Rows
Column
installer       178  36479
scheme_name     153   4910
wpt_name          1      2

,Column,Normalized,Variants,Rows
0,installer,action aid,"(ACTION AID, Action Aid)",2
1,installer,action contre la faim,"(Action Contre La Faim, Action Contre la Faim)",9
2,installer,adra,"(ADRA, Adra)",135
3,installer,af,"(AF, Af)",29
4,installer,africa,"(AFRICA, Africa)",6
5,installer,amboni plantation,"(Amboni Plantation, Amboni plantation)",5
6,installer,amref,"(AMREF, Amref)",443
7,installer,angli,"(ANGLI, Angli)",97
8,installer,anglican church,"(Anglican Church, Anglican church)",6
9,installer,anglican uganda,"(Anglican Uganda, anglican Uganda)",2
10,installer,angrikana,"(ANGRIKANA, Angrikana)",8
11,installer,aqua wel,"(AQUA WEL, AQUA Wel)",2
12,installer,ardhi water well,"(Ardhi Water well, Ardhi water well)",11
13,installer,biore,"(BIORE, BioRe, Biore)",5
14,installer,care international,"(Care international, Care international, care...",24
15,installer,cefa,"(CEFA, Cefa)",90
16,installer,central government,"(CENTRAL GOVERNMENT, Central Government, Centr...",763
17,installer,ch,"(CH, Ch)",35
18,installer,chacha,"(Chacha, chacha)",2
19,installer,china,"(CHINA, China)",9

## Numeric variables and zero placeholders

In [20]:
numeric_columns = column_summary["numeric_columns"]
print("Numeric columns:", numeric_columns)

Numeric columns: ['id', 'amount_tsh', 'gps_height', 'longitude', 'latitude', 'num_private', 'region_code', 'district_code', 'population', 'construction_year']

Zero is not automatically invalid. The unusually frequent zero `gps_height`
values are possible placeholders; they do not establish that the pumps are at
sea level. Negative elevation can be physically valid. Both are counted in the
screening below and retained pending source validation.

`num_private` has 65 distinct values in the raw data, so it is not constant.
Its meaning is unclear in this project. Dropping it is the current feature
selection decision; pass `drop_columns=()` to `clean_data()` to retain it.

In [21]:
display(train_data[numeric_columns].dtypes.rename("Data type"))

id                     int64
amount_tsh           float64
gps_height             int64
longitude            float64
latitude             float64
num_private            int64
region_code            int64
district_code          int64
population             int64
construction_year      int64
Name: Data type, dtype: object

In [22]:
display(column_summary["numeric_summary"])

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,59400.000000,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000,59400.000000,59400.000000
mean,37115.131768,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,15.297003,5.629747,179.909983,1300.652475
std,21453.128371,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,17.587406,9.633649,471.482176,951.620547
min,0.000000,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18519.750000,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,37061.500000,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,12.000000,3.000000,25.000000,1986.000000
75%,55656.500000,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,17.000000,5.000000,215.000000,2004.000000
max,74247.000000,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

In [23]:
# Use the existing audit results instead of recalculating missing counts.
numeric_missing = (
    raw_quality["missing_values"].reindex(numeric_columns).to_frame("Missing Values")
)
display(numeric_missing)

                   Missing Values
id                              0
amount_tsh                      0
gps_height                      0
longitude                       0
latitude                        0
num_private                     0
region_code                     0
district_code                   0
population                      0
construction_year               0

In [24]:
display(train_data[numeric_columns].head(10))

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
0,0,0.0,0,33.125828,-5.118154,0,14,3,0,0
1,1,0.0,1978,34.770717,-9.395642,0,11,4,20,2008
2,2,0.0,0,36.115056,-6.279268,0,1,4,0,0
3,3,10.0,1639,37.147432,-3.187555,0,3,5,25,1999
4,4,0.0,0,36.164893,-6.099289,0,1,4,0,0
5,5,50.0,28,39.286124,-6.972403,0,60,43,6922,0
6,6,0.0,0,33.229880,-3.852983,0,17,3,0,0
7,7,0.0,0,36.313619,-6.719257,0,1,1,0,0
8,8,0.0,0,35.939445,-6.014358,0,1,5,0,0
9,9,0.0,0,31.693371,-2.530703,0,18,8,0,0

### Suspicious values and screening rules

The shared screening reports counts and percentages for placeholders, malformed
values, implausible construction dates, coordinates, and unexpected target
labels. Percentages use all rows; flags can overlap and must not be added as a
total number of bad records.

- Zero population and construction year follow the project's unknown-value rule.
- Flag nonzero construction years before 1900, fractional years, and construction
  after the recording year. These need source review before further correction.
- Flag zero longitude paired with latitude within `1e-6` degrees of zero. The
  broad Tanzania envelope is longitude 29–41 and latitude -12.5–-0.9 degrees;
  it is a screening envelope, not an exact country boundary.
- Count zero and negative elevation separately; neither proves the cause.
- Count literal `"0"`, blank, and unknown tokens in funder and installer fields
  separately from actual missing values.

Retain flagged coordinates, elevations, categorical placeholders and nonzero
year anomalies in the default cleaned data pending verification. Exclude flagged
coordinate placeholders from geospatial analysis. Consider missing-value
representations and reviewed categorical mappings in later preprocessing.

In [25]:
suspicious_values = check_suspicious_values(train_data)
display(suspicious_values.round({"Percent of rows": 2}))

                                                     Rows  Percent of rows
Check
population: non-numeric value                           0             0.00
construction_year: non-numeric value                    0             0.00
gps_height: non-numeric value                           0             0.00
longitude: non-numeric value                            0             0.00
latitude: non-numeric value                             0             0.00
population: zero                                    21381            35.99
population: negative                                    0             0.00
construction_year: zero                             20709            34.86
construction_year: negative                             0             0.00
gps_height: zero                                    20438            34.41
gps_height: negative                                 1496             2.52
construction_year: positive year before 1900            0             0.00
construction_year: fractional year                      0             0.00
date_recorded: unparseable non-missing value            0             0.00
construction_year: after recording year                 9             0.02
coordinates: longitude zero and latitude near zero   1812             3.05
coordinates: outside global bounds                      0             0.00
coordinates: outside broad Tanzania envelope         1812             3.05
funder: literal zero                                  777             1.31
funder: blank or unknown token                          4             0.01
installer: literal zero                               777             1.31
installer: blank or unknown token                       4             0.01
status_group: unexpected non-missing label              0             0.00

## Apply the shared cleaning rules

`clean_data()` uses the same defaults as the standalone `run_pipeline()`:

1. Treat zero `population` and `construction_year` values as missing.
2. Parse `date_recorded` as datetime; invalid dates become `NaT`.
3. Drop `num_private` according to the current project decision.

The default call preserves its input. Rows, IDs, labels and other values remain
available for comparison. Imputation and additional feature selection are
separate modelling decisions.

In [26]:
# Inspect the placeholders before applying the shared rules to a copy.
zero_counts = train_data[["population", "construction_year", "num_private"]].eq(0).sum()
display(zero_counts.rename("Zero values before cleaning"))
cleaned_data = clean_data(train_data)

population           21381
construction_year    20709
num_private          58643
Name: Zero values before cleaning, dtype: int64

In [27]:
print("Raw dimensions:", train_data.shape)
print("Cleaned dimensions:", cleaned_data.shape)
display(cleaned_data.head(10))
cleaned_quality = check_data_quality(cleaned_data, verbose=False)
display(cleaned_quality["missing_values"].rename("Missing values after cleaning"))
print("Duplicate rows excluding id:", cleaned_quality["duplicate_rows"])
display(cleaned_quality["target_distribution"].rename("Pump count after cleaning"))

Raw dimensions: (59400, 41)
Cleaned dimensions: (59400, 40)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,basin,...,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,0,0.0,2012-11-13,Tasaf,0,TASAF,33.125828,-5.118154,Mratibu,Lake Tanganyika,...,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,non functional
1,1,0.0,2011-03-05,Shipo,1978,SHIPO,34.770717,-9.395642,none,Rufiji,...,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
2,2,0.0,2011-03-27,Lvia,0,LVIA,36.115056,-6.279268,Bombani,Wami / Ruvu,...,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,functional
3,3,10.0,2013-06-03,Germany Republi,1639,CES,37.147432,-3.187555,Area 7 Namba 5,Pangani,...,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
4,4,0.0,2011-03-22,Cmsr,0,CMSR,36.164893,-6.099289,Ezeleda,Wami / Ruvu,...,soft,good,dry,dry,shallow well,shallow well,groundwater,hand pump,hand pump,non functional
5,5,50.0,2011-02-26,Private,28,Private,39.286124,-6.972403,Kwa Namaj,Wami / Ruvu,...,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,functional
6,6,0.0,2012-10-20,Government Of Tanzania,0,Government,33.229880,-3.852983,Mission,Internal,...,soft,good,seasonal,seasonal,shallow well,shallow well,groundwater,other,other,non functional
7,7,0.0,2011-03-23,Water,0,Gover,36.313619,-6.719257,Itawi,Rufiji,...,milky,milky,insufficient,insufficient,spring,spring,groundwater,improved spring,improved spring,functional
8,8,0.0,2011-04-07,Water,0,Commu,35.939445,-6.014358,Kwa Chiswagala,Wami / Ruvu,...,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
9,9,0.0,2011-07-12,Ded,0,DED,31.693371,-2.530703,Shule Ya Msingi Nyamirembe A,Lake Victoria,...,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional

scheme_name              28810
population               21381
construction_year        20709
scheme_management         3878
installer                 3655
funder                    3637
public_meeting            3334
permit                    3056
subvillage                 371
wpt_name                     2
latitude                     0
longitude                    0
id                           0
amount_tsh                   0
gps_height                   0
date_recorded                0
ward                         0
lga                          0
district_code                0
region_code                  0
region                       0
basin                        0
recorded_by                  0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group                 0
Name: Missing values after cleaning, dtype: int64

Duplicate rows excluding id: 36

status_group
functional                 32259
non functional             22824
functional needs repair     4317
Name: Pump count after cleaning, dtype: int64

## Compare raw and cleaned columns

The additional missing values represent the zero placeholders and any invalid
dates. `date_recorded` changes from text to datetime, and `num_private` is
reported as dropped. The raw `train_data` remains available for investigation.

In [28]:
cleaned_dictionary = build_data_dictionary(cleaned_data)
cleaning_comparison = rawdata_dictionary.set_index("Column")[
    ["Data Type", "Missing Values"]
].join(
    cleaned_dictionary.set_index("Column")[["Data Type", "Missing Values"]],
    lsuffix=" (raw)",
    rsuffix=" (cleaned)",
    how="outer",
)
cleaning_comparison["Dropped"] = ~cleaning_comparison.index.isin(cleaned_data.columns)
display(cleaning_comparison)

,Data Type (raw),Missing Values (raw),Data Type (cleaned),Missing Values (cleaned),Dropped
Column,,,,,
amount_tsh,float64,0,float64,0.0,False
basin,str,0,str,0.0,False
construction_year,int64,0,float64,20709.0,False
date_recorded,str,0,datetime64[us],0.0,False
district_code,int64,0,int64,0.0,False
extraction_type,str,0,str,0.0,False
extraction_type_class,str,0,str,0.0,False
extraction_type_group,str,0,str,0.0,False
funder,str,3637,str,3637.0,False
gps_height,int64,0,int64,0.0,False
id,int64,0,int64,0.0,False
installer,str,3655,str,3655.0,False
latitude,float64,0,float64,0.0,False
lga,str,0,str,0.0,False
longitude,float64,0,float64,0.0,False
management,str,0,str,0.0,False
management_group,str,0,str,0.0,False
num_private,int64,0,NaN,NaN,True
payment,str,0,str,0.0,False
payment_type,str,0,str,0.0,False
permit,object,3056,object,3056.0,False
population,int64,0,float64,21381.0,False
public_meeting,object,3334,object,3334.0,False
quality_group,str,0,str,0.0,False
quantity,str,0,str,0.0,False
quantity_group,str,0,str,0.0,False
recorded_by,str,0,str,0.0,False
region,str,0,str,0.0,False
region_code,int64,0,int64,0.0,False
scheme_management,str,3878,str,3878.0,False
scheme_name,str,28810,str,28810.0,False
source,str,0,str,0.0,False
source_class,str,0,str,0.0,False
source_type,str,0,str,0.0,False
status_group,str,0,str,0.0,False
subvillage,str,371,str,371.0,False
ward,str,0,str,0.0,False
water_quality,str,0,str,0.0,False
waterpoint_type,str,0,str,0.0,False
waterpoint_type_group,str,0,str,0.0,False
wpt_name,str,2,str,2.0,False

## Findings and next steps

The verified counts, interpretations, cleaning decisions and remaining source
questions are documented in [the data quality findings](../reports/sprint1/data_quality_findings.md).
The [raw data dictionary](../data/raw/data_dictionary.md) describes all input
columns and the target. This audit identifies problems and preserves uncertain
records; source verification, imputation and model preprocessing remain separate
steps. Raw CSVs stay local under `data/raw/` and are excluded from version control.